#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Module: Experiment Tracking
===========================
Lightweight state container to parse and accumulate metrics from 
evaluation runs, preparing them for native Pandas consumption.
Captures the full 3D experiment matrix: Content x Granularity x Domain.

Metadata
--------
:Author: Giovanni G. R. Milan
:Date: 2026-04-19
:Version: 1.0.0
"""

from typing import Dict, Any
from rainfall_acoustic_classification.utils import get_standard_logger

logger = get_standard_logger("ExperimentTracker")

class ExperimentTracker:
    """
    Accumulates metrics from multiple model evaluations into a standard list 
    of dictionaries, avoiding global variable leakage in Jupyter Notebooks.

    Attributes
    ----------
    records : list of dict
        An internal list storing the parsed metrics and metadata for each 
        evaluation run.
    """

    def __init__(self) -> None:
        """
        Initializes an empty registry for the experimental runs.
        """
        self.records = []
        logger.info("Experiment Tracker initialized. Clean slate.")

    def add_run(
        self, 
        algorithm: str, 
        content: str,
        granularity: str, 
        domain: str, 
        evaluation_results: Dict[str, Any]
    ) -> None:
        """
        Parses evaluation metrics and appends the run to the internal records.

        Parameters
        ----------
        algorithm : str
            The name or acronym of the model architecture (e.g., 'RF', 'XGB').
        content : str
            The acoustic content setting evaluated (e.g., 'dry/wet', 'wet', 'dry').
        granularity : str
            The target class resolution (e.g., 'Binary', '3-Class', '5-Class').
        domain : str
            The testing domain or evaluation scope (e.g., 'UECE', 'IDSM').
        evaluation_results : dict of {str: Any}
            The dictionary of metrics generated by `ModelEvaluator.evaluate()`.
            Must contain keys starting with 'f1_' and 'pr_auc_'.

        Returns
        -------
        None
        """
        # Extract the core metrics dynamically (agnostic to 'macro' or 'micro' naming)
        f1_keys = [k for k in evaluation_results.keys() if k.startswith('f1_')]
        pr_keys = [k for k in evaluation_results.keys() if k.startswith('pr_auc_')]

        self.records.append({
            'Algorithm': algorithm.upper(),
            'Content': content,
            'Granularity': granularity,
            'Domain': domain,
            'f1_macro': evaluation_results[f1_keys[0]] if f1_keys else None,
            'pr_auc_macro': evaluation_results[pr_keys[0]] if pr_keys else None
        })
        
        logger.info(f"Recorded Run -> [{algorithm.upper()} | {content} | {granularity} | {domain}]")

if __name__ == '__main__':
    pass