#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Module: Feature Engineering Plots
=================================
Provides static, publication-ready visualizations for feature selection,
correlation analysis, and scaling validation. Aligned with the global 
Visualization Engine.

Metadata
--------
:Author: Giovanni G. R. Milan
:Date: 2026-04-17
:Version: 2.1.0
"""

import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from typing import List, Optional, Any, Dict
from sklearn.ensemble import RandomForestClassifier

from rainfall_acoustic_classification.utils import get_standard_logger

logger = get_standard_logger("FeaturePlots")


def plot_correlation_heatmap(
    df: pd.DataFrame, 
    threshold: float = 0.85,
    selected_features: Optional[List[str]] = None,
    title: str = "Acoustic Feature Correlation Matrix",
    save_path: Optional[str] = None
) -> None:
    """
    Plots a lower-triangle correlation heatmap, highlighting features that
    exceed the collinearity threshold.

    Parameters
    ----------
    df : pd.DataFrame
        The feature matrix (X) to analyze.
    threshold : float, default=0.85
        The correlation limit. Values above this are visually isolated.
    title : str, default="Acoustic Feature Correlation Matrix"
        The title of the plot.
    save_path : str, optional
        If provided, saves the figure to this filepath.
    """
    logger.info("Generating Correlation Heatmap...")
    
    corr = df.corr().abs() 
    mask = np.triu(np.ones_like(corr, dtype=bool))
    
    fig, ax = plt.subplots(figsize=(14, 12))
    
    # 2. O Segredo: Remover o 'center'. 
    # Usei 'Spectral_r' (_r de reverso) para que o 1.0 fique Vermelho e o 0.0 fique Azul.
    # Se preferir o contrário, basta tirar o '_r'.
    sns.heatmap(
        corr, mask=mask, cmap='Spectral_r', vmin=0.0, vmax=1.0, 
        square=True, linewidths=.5, 
        cbar_kws={"shrink": .5, "label": "Absolute Correlation (|Pearson|)"}, ax=ax
    )
    
    # 3. CORREÇÃO DO MATPLOTLIB: Modifica in-place iterando em cada eixo separadamente
    if selected_features:
        for label in ax.get_xticklabels():
            if label.get_text() in selected_features:
                label.set_weight('bold')
                label.set_color('black')
                
        for label in ax.get_yticklabels():
            if label.get_text() in selected_features:
                label.set_weight('bold')
                label.set_color('black')

    ax.set_title(title, fontsize=16, pad=20)
    plt.tight_layout()
    
    if save_path:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        fig.savefig(save_path, dpi=300, bbox_inches='tight')
        logger.info(f"Correlation heatmap saved to {save_path}")
    else:
        plt.show()
    plt.close(fig)


def plot_fisher_scores(
    df_tracking: pd.DataFrame, 
    top_n: int = 20, 
    title: str = "Fisher F-Score (ANOVA) - Class Separability",
    save_path: Optional[str] = None
) -> None:
    """
    Plots the Fisher Scores from the tracking DataFrame to demonstrate linear class separability.
    
    Parameters
    ----------
    df_tracking : pd.DataFrame
        The master tracking DataFrame generated by VectorSelector.get_metrics_report().
    top_n : int, default=20
        Number of top features to plot.
    title : str
        The title of the plot.
    save_path : Optional[str]
        Directory path to save the PDF/PNG artifact.
    """
    logger.info(f"Generating Fisher Score Plot (Top {top_n})...")
    
    # 1. Filtra dados inválidos e pega o Top N
    df_fisher = df_tracking.dropna(subset=['Fisher_Score']).copy()
    
    # A tabela provavelmente já vem ordenada da classe, mas ordenamos 
    # novamente aqui por segurança antes do head(top_n)
    df_fisher = df_fisher.sort_values(by='Fisher_Score', ascending=False).head(top_n)
    
    # 2. Configuração da Figura
    fig, ax = plt.subplots(figsize=(10, 8))
    sns.barplot(data=df_fisher, x='Fisher_Score', y='Feature_Name', palette='viridis', ax=ax)
    
    # 3. Estilização
    ax.set_title(title, fontsize=16, pad=15)
    ax.set_xlabel("F-Value (Higher = Better Visual Separation in Boxplots)", fontsize=12)
    ax.set_ylabel("Acoustic Feature", fontsize=12)
    plt.tight_layout()
    
    # 4. Persistência
    if save_path:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        fig.savefig(save_path, dpi=300, bbox_inches='tight')
    else:
        plt.show()
        
    plt.close(fig)


def plot_selection_rationale(
    fisher_scores: np.ndarray,
    gini_importances: np.ndarray,
    feature_names: List[str],
    selected_mask: List[str],
    title: str = "Feature Selection Rationale: Fisher vs Gini",
    save_path: Optional[str] = None
) -> None:
    """
    Scatter plot crossing Fisher Score and Gini Importance.
    Respects the project's architecture:
    - Discarded features: Gray crosses ('x').
    - Selected features: Spectral palette circles ('o') with names in the legend.
    """
    logger.info("Generating Selection Rationale Plot...")
    
    # 1. Estruturação dos Dados
    df = pd.DataFrame({
        'Feature': feature_names,
        'Fisher': fisher_scores,
        'Gini': gini_importances,
        'Status': ['Selected' if f in selected_mask else 'Discarded' for f in feature_names]
    })

    df_discarded = df[df['Status'] == 'Discarded']
    df_selected = df[df['Status'] == 'Selected']

    fig, ax = plt.subplots(figsize=(12, 8))

    # 2. Plota os Descartados (Fundo cinza)
    ax.scatter(
        df_discarded['Fisher'], 
        df_discarded['Gini'], 
        marker='x', 
        color='gray', 
        alpha=0.6, 
        s=60, 
        label='Discarded'
    )

    # ==============================================================================
    # O SEGREDO DO CONTRASTE: Fatiando a paleta matematicamente
    # ==============================================================================
    features_unicas = df_selected['Feature'].unique()
    # Pega exatamente N cores com a distância máxima possível entre elas dentro do Spectral
    cores_distantes = sns.color_palette("Spectral", n_colors=len(features_unicas))
    # Cria um dicionário amarrando cada feature à sua cor isolada
    paleta_forcada = dict(zip(features_unicas, cores_distantes))
    # ==============================================================================

    # 3. Plota as Selecionadas usando a paleta forçada
    sns.scatterplot(
        data=df_selected, 
        x='Fisher', 
        y='Gini', 
        hue='Feature', 
        palette=paleta_forcada, # Usa o nosso dicionário de cores extremas
        s=150, 
        edgecolor='black',
        linewidth=1,
        alpha=1.0,
        ax=ax
    )

    # 4. Ajustes Estéticos
    ax.set_title(title, fontsize=16, pad=15)
    ax.set_xlabel("Fisher Score (Linear Separation)", fontsize=12)
    ax.set_ylabel("Gini Importance (Tree Split Power)", fontsize=12)
    
    ax.legend(bbox_to_anchor=(1.02, 1), loc='upper left', title="Selected Features", frameon=True)
    ax.grid(True, linestyle='--', alpha=0.5)
    
    plt.tight_layout()
    
    if save_path:
        import os
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        fig.savefig(save_path, dpi=300, bbox_inches='tight')
    else:
        plt.show()
    plt.close(fig)


def plot_feature_importance(
    rf_model: RandomForestClassifier, 
    feature_names: List[str], 
    top_n: int = 20,
    title: str = "Random Forest Feature Importance (Gini)",
    save_path: Optional[str] = None
) -> None:
    """
    Plots a horizontal bar chart of the top N features based on Gini impurity reduction.

    Parameters
    ----------
    rf_model : RandomForestClassifier
        The fitted Random Forest model from the selection pipeline.
    feature_names : List[str]
        The names of the features that were fed into the Random Forest.
    top_n : int, default=20
        The maximum number of top features to display.
    title : str, default="Random Forest Feature Importance (Gini)"
        The title of the plot.
    save_path : str, optional
        If provided, saves the figure to this filepath.
    """
    logger.info(f"Generating Feature Importance Plot (Top {top_n})...")
    
    importances = rf_model.feature_importances_
    indices = np.argsort(importances)[::-1][:top_n]
    
    sorted_features = [feature_names[i] for i in indices]
    sorted_importances = importances[indices]

    fig, ax = plt.subplots(figsize=(10, 8))
    sns.barplot(x=sorted_importances, y=sorted_features, palette="viridis", ax=ax)
    
    ax.set_title(title, fontsize=16)
    ax.set_xlabel("Mean Decrease in Impurity (Gini Importance)", fontsize=12)
    ax.set_ylabel("Acoustic Metrics", fontsize=12)
    ax.grid(axis='x', linestyle='--', alpha=0.7)
    plt.tight_layout()
    
    if save_path:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        fig.savefig(save_path, dpi=300, bbox_inches='tight')
        logger.info(f"Feature importance plot saved to {save_path}")
    else:
        plt.show()
    plt.close(fig)


def plot_scaled_distributions(
    X: pd.DataFrame, 
    y: pd.Series, 
    color_map: Dict[str, str],
    class_order: List[str],
    features_to_plot: Optional[List[str]] = None,
    title: str = "Scaled Feature Distributions (Z-Scores)",
    save_path: Optional[str] = None
) -> None:
    """
    Creates Violin Plots for selected features to validate standardization.
    Colors and ordering are strictly delegated to the central Visualization Engine.

    Parameters
    ----------
    X : pd.DataFrame
        The standardized feature matrix.
    y : pd.Series
        The target labels.
    color_map : Dict[str, str]
        Mapping of class names to hexadecimal color codes (from engine.py).
    class_order : List[str]
        The authoritative order of classes (from engine.py).
    features_to_plot : List[str], optional
        Specific features to visualize. If None, plots the first 6.
    title : str, default="Scaled Feature Distributions (Z-Scores)"
        The title of the plot.
    save_path : str, optional
        If provided, saves the figure to this filepath.
    """
    logger.info("Generating Scaled Distributions Plot...")
    
    if features_to_plot is None:
        features_to_plot = X.columns[:6].tolist()
        
    plot_df = X[features_to_plot].copy()
    plot_df['Target'] = y.values
    
    melted_df = plot_df.melt(id_vars='Target', var_name='Feature', value_name='Z-Score')
    
    fig, ax = plt.subplots(figsize=(14, 8))
    sns.violinplot(
        data=melted_df, 
        x='Feature', 
        y='Z-Score', 
        hue='Target', 
        hue_order=class_order,
        palette=color_map, 
        split=False, 
        inner='quartile',
        ax=ax
    )
    
    # Reference lines for Z-score validation
    ax.axhline(0, color='black', linestyle='-', linewidth=1, alpha=0.5)
    ax.axhline(1, color='red', linestyle='--', linewidth=1, alpha=0.5)
    ax.axhline(-1, color='red', linestyle='--', linewidth=1, alpha=0.5)
    
    ax.set_title(title, fontsize=16)
    ax.set_xlabel("Acoustic Metrics", fontsize=12)
    ax.set_ylabel("Standardized Value (Z-Score)", fontsize=12)
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')
    ax.legend(title='Category', bbox_to_anchor=(1.05, 1), loc='upper left')
    
    plt.tight_layout()
    
    if save_path:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        fig.savefig(save_path, dpi=300, bbox_inches='tight')
        logger.info(f"Scaled distributions plot saved to {save_path}")
    else:
        plt.show()
    plt.close(fig)


def plot_survival_scatter_matrix(
    X: pd.DataFrame, 
    y: pd.Series, 
    color_map: Dict[str, str],
    class_order: List[str],
    features_to_plot: Optional[List[str]] = None,
    title: str = "Survival Feature Scatter Matrix",
    save_path: Optional[str] = None
) -> None:
    """
    Displays a static pairplot for the surviving features after selection.
    Respects global visualization engine parameters.

    Parameters
    ----------
    X : pd.DataFrame
        The post-selection feature matrix.
    y : pd.Series
        The target labels.
    color_map : Dict[str, str]
        Mapping of class names to hexadecimal color codes (from engine.py).
    class_order : List[str]
        The authoritative order of classes (from engine.py).
    features_to_plot : List[str], optional
        The specific features to plot. If None, plots up to 4 features.
    title : str, default="Survival Feature Scatter Matrix"
        The title of the plot.
    save_path : str, optional
        If provided, saves the figure to this filepath.
    """
    if features_to_plot is None:
        features_to_plot = X.columns[:4].tolist()
        
    logger.info(f"Generating Scatter Matrix for features: {features_to_plot}")
    
    plot_df = X[features_to_plot].copy()
    plot_df['Target'] = y.values
    
    g = sns.pairplot(
        plot_df,
        vars=features_to_plot,
        hue='Target',
        hue_order=class_order,
        palette=color_map,
        diag_kind='kde',
        plot_kws={'alpha': 0.6, 's': 20, 'edgecolor': 'none'}
    )
    
    g.fig.suptitle(title, y=1.02, fontsize=16)
    
    if save_path:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        g.fig.savefig(save_path, dpi=300, bbox_inches='tight')
        logger.info(f"Scatter matrix saved to {save_path}")
    else:
        plt.show()
    plt.close(g.fig)


def plot_correlation_comparison(
    df_pre: pd.DataFrame, 
    df_post: pd.DataFrame, 
    threshold: float = 0.85,
    title: str = "Correlation Matrix: Pre vs. Post Filtering",
    save_path: Optional[str] = None
) -> None:
    """
    Plots a side-by-side comparison of the correlation matrices before and 
    after the CollinearityFilter is applied.

    Parameters
    ----------
    df_pre : pd.DataFrame
        The feature matrix before filtering.
    df_post : pd.DataFrame
        The feature matrix after filtering.
    threshold : float, default=0.85
        The correlation limit.
    title : str, default="Correlation Matrix: Pre vs. Post Filtering"
        The main title of the figure.
    save_path : str, optional
        If provided, saves the figure to this filepath.
    """
    logger.info("Generating Pre vs. Post Correlation Comparison...")
    
    fig, axes = plt.subplots(1, 2, figsize=(20, 8))
    cmap = sns.diverging_palette(230, 20, as_cmap=True)
    
    for ax, df, state in zip(axes, [df_pre, df_post], ["Pre-Filtering", "Post-Filtering"]):
        corr = df.corr().abs()
        mask = np.triu(np.ones_like(corr, dtype=bool))
        
        sns.heatmap(
            corr, mask=mask, cmap=cmap, vmax=1.0, vmin=0.0, 
            center=threshold, square=True, linewidths=.5, 
            cbar_kws={"shrink": .5}, ax=ax
        )
        ax.set_title(f"{state} ({df.shape[1]} features)", fontsize=14)
        
    fig.suptitle(title, fontsize=18, y=1.05)
    plt.tight_layout()
    
    if save_path:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        fig.savefig(save_path, dpi=300, bbox_inches='tight')
        logger.info(f"Correlation comparison saved to {save_path}")
    else:
        plt.show()
    plt.close(fig)


def plot_feature_stability(
    stability_data: Dict[str, int],
    title: str = "Feature Survival across Granularities",
    save_path: Optional[str] = None
) -> None:
    """
    Plots a line/bar chart showing how many features survive the selection 
    pipeline across different target granularities.

    Parameters
    ----------
    stability_data : Dict[str, int]
        A dictionary mapping granularity names to the number of surviving features.
    title : str, default="Feature Survival across Granularities"
        The title of the plot.
    save_path : str, optional
        If provided, saves the figure to this filepath.
    """
    logger.info("Generating Feature Stability Plot...")
    
    labels = list(stability_data.keys())
    counts = list(stability_data.values())
    
    fig, ax = plt.subplots(figsize=(8, 5))
    
    sns.barplot(x=labels, y=counts, palette="mako", alpha=0.7, ax=ax)
    ax.plot(labels, counts, color='black', marker='o', linewidth=2, markersize=8)
    
    ax.set_title(title, fontsize=14)
    ax.set_ylabel("Number of Retained Features", fontsize=12)
    ax.set_xlabel("Target Granularity", fontsize=12)
    ax.set_ylim(0, max(counts) + (max(counts) * 0.2))
    
    for i, count in enumerate(counts):
        ax.text(i, count + 0.5, str(count), ha='center', va='bottom', fontsize=11, fontweight='bold')
        
    ax.grid(axis='y', linestyle='--', alpha=0.5)
    plt.tight_layout()
    
    if save_path:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        fig.savefig(save_path, dpi=300, bbox_inches='tight')
        logger.info(f"Feature stability plot saved to {save_path}")
    else:
        plt.show()
    plt.close(fig)


def plot_individual_boxplots(
    X: pd.DataFrame, 
    y: pd.Series, 
    color_map: Dict[str, str],
    class_order: List[str],
    save_dir: Optional[str] = None
) -> None:
    """
    Generates and saves individual boxplots for every feature in X, grouped by y.
    Strictly follows the engine's color and ordering definitions.

    Parameters
    ----------
    X : pd.DataFrame
        The feature matrix (usually unscaled for interpretable physical units).
    y : pd.Series
        The target labels.
    color_map : Dict[str, str]
        Mapping of class names to hexadecimal color codes.
    class_order : List[str]
        The desired order of classes for the x-axis and color mapping.
    save_dir : str, optional
        The directory where the individual PNGs will be saved.
    """
    logger.info(f"Generating Individual Boxplots for {X.shape[1]} features...")
    
    plot_df = X.copy()
    plot_df['Target'] = y.values
    
    for feature in X.columns:
        fig, ax = plt.subplots(figsize=(8, 6))
        
        sns.boxplot(
            data=plot_df,
            x='Target',
            y=feature,
            hue='Target',
            palette=color_map,
            order=class_order,
            hue_order=class_order,
            legend=False,
            flierprops=dict(marker='o', markersize=4, markerfacecolor='red', markeredgecolor='red', alpha=0.5),
            ax=ax
        )
        
        ax.set_title(f"Distribution of {feature}", fontsize=14)
        ax.set_xlabel("Category", fontsize=12)
        ax.set_ylabel(feature, fontsize=12)
        ax.grid(axis='y', linestyle='--', alpha=0.7)
        plt.tight_layout()
        
        if save_dir:
            os.makedirs(save_dir, exist_ok=True)
            safe_name = feature.replace(' ', '_').replace('/', '_')
            file_path = os.path.join(save_dir, f"boxplot_{safe_name}.png")
            fig.savefig(file_path, dpi=300, bbox_inches='tight')
            plt.close(fig)
        else:
            plt.show()
            plt.close(fig)
            
    if save_dir:
        logger.info(f"All individual boxplots saved to {save_dir}")

if __name__ == '__main__':
    pass